# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kiko"

# URL
baseurl:            "/"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           ""

# Sass
sass:
  style:            :compressed

# Collections
collections:
- songs

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "songs"
    values:
      layout:       "song"
